"use client";
import {FormEvent,useMemo,useState} from "react";
const assets=[
{id:"CODE-001",cluster:"Progressive delivery",path:"packages/release-guard/src/canary.ts",symbol:"createCanaryPlan",owner:"Leena Rao",jira:"LOOP-42",behavior:"Builds account cohorts, evaluates health gates and triggers rollback.",consumers:"checkout-api · search-api · inventory-worker",keys:["canary","cohort","feature flag","rollout","rollback","progressive"]},
{id:"CODE-002",cluster:"Deployment verification",path:"packages/release-guard/src/verify.ts",symbol:"verifyDeploymentHealth",owner:"Leena Rao",jira:"LOOP-42",behavior:"Checks error rate, p95 latency and business KPI deltas after deployment.",consumers:"deploy-orchestrator",keys:["verify","health","error rate","latency","deployment","rollback"]},
{id:"CODE-003",cluster:"Service catalog",path:"services/catalog/src/ownership.ts",symbol:"resolveServiceOwner",owner:"Vikram Rao",jira:"ENG-214",behavior:"Resolves canonical service owner, tier, runbook and dependency metadata.",consumers:"developer-portal · incident-bot",keys:["service owner","catalog","runbook","dependency","portal","ownership"]},
{id:"CODE-004",cluster:"Incident learning",path:"tools/incident-linker/index.py",symbol:"extract_failure_taxonomy",owner:"Kabir Malhotra",jira:"LOOP-63",behavior:"Extracts service IDs, repeated failure modes and runbook references from postmortems.",consumers:"incident-knowledge-index",keys:["incident","postmortem","failure","taxonomy","runbook","parser"]}];
const sample=`Title: Add automated canary rollout verification\n\nCreate a helper that gradually releases a deployment to account cohorts. Check error rate and p95 latency, then automatically roll back when the health threshold fails.`;
export default function CodeReview(){const[input,setInput]=useState(sample);const[checked,setChecked]=useState(false);const matches=useMemo(()=>assets.map(a=>({...a,score:a.keys.filter(k=>input.toLowerCase().includes(k)).length})).filter(a=>a.score>0).sort((a,b)=>b.score-a.score),[input]);function run(e:FormEvent){e.preventDefault();setChecked(true)}return <main className="prGuard"><header><a href="/">ECHOCHECK</a><span>PR GUARD / CV1</span><b>CODE PRIOR ART</b></header><section className="prHero"><p>06 / BEFORE THE PULL REQUEST</p><h1>Has this code<br/>already been written?</h1><p>Paste a PR title, description or diff. EchoCheck searches existing behavior—not only filenames—and connects it to the Jira decision and current owner.</p></section><section className="prWorkspace"><form onSubmit={run}><label>PROPOSED PULL REQUEST</label><textarea value={input} onChange={e=>{setInput(e.target.value);setChecked(false)}}/><button>CHECK FOR DUPLICATE IMPLEMENTATION ↗</button></form><aside>{!checked?<div className="prIdle"><span>⌁</span><h2>Ready to inspect.</h2><p>The code dump contains reusable services for progressive delivery, service ownership and incident learning.</p></div>:matches.length?<><div className="prVerdict"><span>POTENTIAL DUPLICATE</span><b>{Math.min(97,78+matches[0].score*4)}%</b></div><h2>Reuse existing implementation.</h2>{matches.slice(0,2).map(m=><article key={m.id}><div><span>{m.id} · {m.jira}</span><em>{m.cluster}</em></div><h3>{m.symbol}()</h3><code>{m.path}</code><p>{m.behavior}</p><dl><div><dt>OWNER</dt><dd>{m.owner}</dd></div><div><dt>USED BY</dt><dd>{m.consumers}</dd></div></dl></article>)}<div className="prAction"><b>RECOMMENDED ACTION</b><p>Import and extend release-guard. Add the novel threshold configuration to LOOP-42 instead of creating a second rollout abstraction.</p></div></>:<div className="prIdle"><span>✓</span><h2>No duplicate found.</h2></div>}</aside></section></main>}
